# Site settings
title: "Piyush Kumar - Portfolio"
description: "Personal portfolio website of Piyush Kumar"
baseurl: "" # For user/organization site
url: "https://piyushk124.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from Jekyll build
exclude:
  - README.md
  - LICENSE
  - .gitignore